export function json(res,status,data){res.status(status).setHeader('Content-Type','application/json');return res.end(JSON.stringify(data));}
export async function readBody(req){if(req.body&&typeof req.body==='object')return req.body;let raw='';for await(const chunk of req)raw+=chunk;if(!raw)return{};try{return JSON.parse(raw)}catch{return{}}}
export function env(name){return String(process.env[name]||'').trim()}
export function requireEnv(names){for(const n of names){const v=env(n);if(v)return v}throw new Error(`Missing environment variable: ${names.join(' or ')}`)}
export function esc(s=''){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
export function supabaseHeaders(key,extra={}){return {'apikey':key,'Authorization':`Bearer ${key}`,...extra}}
export async function supabaseRequest(path,options={}){const base=requireEnv(['SUPABASE_URL']).replace(/\/$/,'');const key=requireEnv(['SUPABASE_SECRET_KEY','SUPABASE_SERVICE_ROLE_KEY']);const r=await fetch(`${base}/rest/v1/${path}`,{...options,headers:supabaseHeaders(key,options.headers||{})});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok){const e=new Error(data?.message||data?.hint||data?.error||`Supabase HTTP ${r.status}`);e.status=r.status;throw e}return data}
export function caseNumber(id){const n=Number(id);return `UNDO-${String(Number.isFinite(n)?n:Math.floor(Math.random()*900000+100000)).padStart(6,'0')}`}
export async function sendEmail({to,subject,html,replyTo}){const key=env('RESEND_API_KEY');if(!key)return{sent:false,reason:'RESEND_API_KEY missing'};const from=env('EMAIL_FROM')||'UNDO <onboarding@resend.dev>';const body={from,to:[to],subject,html};if(replyTo)body.reply_to=replyTo;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify(body)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(data?.message||`Resend HTTP ${r.status}`);return{sent:true,id:data?.id||null}}
export function admin(req){const token=env('ADMIN_TOKEN');const auth=String(req.headers.authorization||'');return token&&auth===`Bearer ${token}`}
